### PR TITLE
Update related packages

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Add hBayesDM to related projects.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by riddell-stan** [comment]
Cool!

Should we perhaps make a separate section for packages *using* pystan (vs. similar ones)?

**Review by riddell-stan — APPROVED** [review]

**Comment by ahartikainen** [comment]
I think we could do that. Do you want to edit this branch?

**Comment by riddell-stan** [comment]
How does that look?

**Comment by ahartikainen** [comment]
Looks good. Maybe we could also move bambi under that section?

**Pull request merged**
