### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by edwinnglabs**
#### Summary:
Proposed to include Orbit in the related projects section

#### Intended Effect:
N/A
#### How to Verify:
N/A
#### Side Effects:
N/A
#### Documentation:
N/A
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Can this point to develop branch?

**Comment by edwinnglabs** [comment]
> Can to point to develop branch?

How about our [github page](https://uber.github.io/orbit/)?

**Comment by edwinnglabs** [comment]
> Can this point to develop branch?

Updated the link to point to dev branch

**Comment by riddell-stan** [comment]
It really needs to point to the develop branch, not `readthedocs`.

If you want people to learn about this software you might consider posting a description of it to the Stan forums. https://discourse.mc-stan.org/

**Comment by edwinnglabs** [comment]
@riddell-stan do you mind reviewing this?

**Comment by riddell-stan** [comment]
The target branch is correct. Thanks.

This is a simple change and needs to be a single commit (not six). Try squashing it. You can also start again from scratch if that's easier.

**Comment by edwinnglabs** [comment]
I am creating a separate one to make a cleaner commit

**Pull request closed without merging**
