### PR TITLE
Add some troubleshooting the end of the installation instructions

### PR DESCRIPTION
**Pull request by Manishearth**
#### Summary:

A friend was having trouble with their install, and in helping I myself also bumped into some issues. It seems like we should at least add some troubleshooting steps to help with these.

The compiler not working is a particularly nefarious kind of bug because pystan will install successfully, it just won't _work_ (so downstream packages will report bugs).

#### Intended Effect:

Better installation experience for new users.

#### How to Verify:
None, this is documentation
#### Side Effects:

None, this is documentation
#### Documentation:

This _is_ documentation

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Manish Goregaokar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by Manishearth** [comment]
It might also be worth including non-conda install instructions: for linux this is simply "install the appropriate python3 headers package, `python3-dev` or `python3.x-dev` on Debian".

**Comment by riddell-stan** [comment]
Thanks.

I'd like to know more about this problem. Does pystan really not compile without the python-dev package on Linux?

**Comment by Manishearth** [comment]
@riddell-stan it might with the conda setup. But the documentation says that conda isn't necessary, only preferred for managing c++ toolchains. I already had a c++ toolchain and didn't want to set up a second package manager, so I tried without it, and saw some inscrutable errors in a downstream dep until I ran it with `verbose=True` and realized Python.h was missing.

The OSX XCode issue happens even when using conda.

**Review by ahartikainen — APPROVED** [review]

**Comment by ahartikainen** [comment]
Thanks for the PR. Troubleshooting instructions are always important.

**Pull request merged**
