### PR TITLE
Enable GPU

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Needs some extra handling from the user still. After that, hangs somewhere between linking and python process (on Windows).

Add `extra_link_args`, which is empty by default.

#### Intended Effect:

Enable GPU functionality.

#### How to Verify:

Compile and see GPU usage

#### Side Effects:

None: If GPU settings are not defined, then works normally.

#### Documentation:

Add instructions how to use.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Before merging, I think we should test this (doc example model) is working at least on Windows and Linux with suitable GPUs.

**Comment by ahartikainen** [comment]
Oh, I forgot, that this does not currently work on Windows, but I think 2.20 should have fixed code.

So I think this should go after Stan 2.20 has been merged.

**Comment by ahartikainen** [comment]
Maybe we could force c++ with some flags (opencl should need g++)

https://stackoverflow.com/questions/172587/what-is-the-difference-between-g-and-gcc

**Comment by riddell-stan** [comment]
Closing this before marking this repo as archived. PyStan 3 will be released on March 25, 2021.

**Pull request closed without merging**
