### PR TITLE
Update cvodes branch to 2.22.1.0dev

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Sync cvodes with the latest github develop

#### Intended Effect:

When cvodes branch is in-sync with the develop, then they don't need to manually sync submodules.

#### How to Verify:

Tests are passed.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
tbh, this is still a mess.

But it works, and let users use cvodes with pystan 2.

compiling (+linking) times are really long on Windows.

**Comment by riddell-stan** [comment]
Is this easier to use than getting PyStan 3 working under WSL2?

**Comment by ahartikainen** [comment]
I would say no.

But there are users who can't access WSL.

I only updated this, so we don't need to answer why cvodes branch fails to compile.

**Comment by riddell-stan** [comment]
I agree that it would be good to have the `cvodes` branch in a state which works. Thanks for working on this.

**Pull request merged**
